###########################################
# data parameters
###########################################
--- !data
image_shape: [384, 384]

datasets:
  - name: ava
    data_dir: /media/admin-u/data/products
    train_files: "train_data/*/train.txt"
    tfrecord_files: tfrecords/*.records
    weight: 1.
    overwrite_tfrecord: false

labels_csv: /media/admin-u/data/products/products.csv
out_labels: ./labels.csv

###########################################
# training parameters
###########################################
--- !train
is_training: true
model_dir: './models'
num_epochs: 0
learning_rate: 0.001
learning_rate_decay:
  decay_steps: 3000
  decay_rate: 0.97

batch_size: 16
shuffle: true

augmentation:
  random_rotate: true
  random_brightness: true
  random_contrast: true
  random_hue: true
  random_gaussian_noise: true

optimizer:
  name: adam
  params:
    beta1: 0.9
    beta2: 0.999
    epsilon: 1e-8

filenames_shuffle_buffer_size: 100
num_parallel_map_calls: 12  # ~ num of CPU cores or less
num_readers: 32
read_block_length: 64
shuffle_buffer_size: 131072
prefetch_size: 64  # ~ 2 x batch-size


bbox_clf_weight: 10.
bbox_reg_weight: 1.

warm_start: true
warm_start_path: ./models/latest/model.ckpt-242858

quantize: False

###########################################
# model parameters
###########################################
--- !model
model_name: mobilenet_obj
input_shape: [384, 384]
output_shape: [48, 48]
# output_stride: 8

depth_multiplier: 1.
min_depth: 8

# in top-down format
base_anchor_sizes: [32, 64, 128]
anchor_strides: [8, 16, 32]

anchor_scales: [1., 1.2599, 1.5874]
anchor_ratios: [.5, 1., 2.]

unmatched_threshold: 0.4
matched_threshold: 0.6
force_match_for_gt_bbox: true
scale_factors: [10., 5.]

skip_layers:
  - layer_7
  - layer_11
  - layer_17

fpn_depth: 96


###########################################
# inference parameters
###########################################
--- !infer
model_dir: models/latest
frozen_model: frozen_model.pb
network_input_shape: [576, 896]  # [384, 384]
products_csv: '/media/storage/datasets/products/products.csv'

top_k: 10

# format for frame crops is [y_min, x_min, y_max, x_max]
# all coordinates normalized wrt height of the full frame
frame_crops:
#  - [0., 1.1, .8, 1.9]
  - [0., 0., 1., 1.56]
#   - [0.3, .3, 1., 1.]
#   - [0.140, 0.390, 0.530, 0.780]
#   - [0.180, 0.720, 0.540, 1.080]

# input_type can be images, video, camera or http
input_type: images
# images can be a list or use *
# images: /media/easystore/TrainData/Walmart/Round1/Recording_2/20180308_*.jpg
# images: /media/easystore/TrainData/Lab/April20/Recording_44/20180420_*.jpg
images: ['/media/storage/AVAretail/MasterCardShelf/transformed.png']

video: /media/easystore/TrainData/Lab/April20/Recording_44/20180420_0000000.avi

# camera: http://root:123456@192.168.1.24/mjpg/video.mjpg
camera: http://root:amrelirox@192.168.1.24/mjpg/video.mjpg
camera_capture_interval: 0.25  # in seconds

display_bbox: true

